task: tagger
batchsz: 10
conll_output: conll-elmo-bio.conll
charsz: 30
unif: 0.1

preproc: 
    mxlen: -1
    mxwlen: -1
    lower: false 

backend: tensorflow
dataset: conll-bio

loader: 
    reader_type: conllcased

model: 
    model_type: elmo
    cfiltsz: [3]
    hsz: 256
    wsz: 30
    dropout: 0.5
    rnntype: blstm
    layers: 2
    crf_mask: true
    crf: 1


word_embeddings: 
    label: glove-6B-100

train: 
    epochs: 50
    optim: sgd
    eta: 0.015
    mom: 0.9
    patience: 15
    early_stopping_metric: f1
    clip: 5.0
    span_type: bio
